//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGames2NET.Settings.Games.Chess {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Graphics : global::System.Configuration.ApplicationSettingsBase {
        
        private static Graphics defaultInstance = ((Graphics)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Graphics())));
        
        public static Graphics Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SquareSize {
            get {
                return ((int)(this["SquareSize"]));
            }
            set {
                this["SquareSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SquareMargin {
            get {
                return ((int)(this["SquareMargin"]));
            }
            set {
                this["SquareMargin"] = value;
            }
        }
    }
}
